### ISSUE TITLE
1.0 Roadmap

### ISSUE THREAD

**Issue by birbe** [wgpu-mc/wgpu-mc#103]
Putting these here as a general reference to what needs to be done before a stable release can be made

- [ ] Complete entities #87 
- [ ] Fluid rendering #20 
- [ ] Render layers (translucency with z-sorting, fluids, etc) #20 
- [ ] Hand rendering
- [ ] Integrate item rendering and block rendering in GUIs
- [ ] Particles
- [ ] Block colors (grass, fluids)
- [ ] Performance improvements (stuttering, chunk baking speed)
- [ ] Complete block meshing (rotation, respect UV settings in the JSON)
